name: Action Test3_2
on:
        push:
                branches:
                     - main
jobs:
        check-TrustedTypes-in-js_2:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2

                        - name: Checkout codemods
                          uses: actions/checkout@v2
                          with:
                                repository: t0kapo/tt_codemod
                                path: tt_codemod

                        - name: Check policy in JavaScript
                          id: tt
                          uses: t0kapo/action_jscodeshift@v0.9
                          with:
                                codemod: tt_codemod/codemods/transform_documentwrite.js
                                transform: static/js/document_write.js
                                policyname: a_policy

                        - uses: stefanzweifel/git-auto-commit-action@v4.12.0
                          with:
                                  file_pattern: static/js/*.js
                                  commit_message: Checked tt and policy.
