name: Action Test3
on:
        push:
                branches:
                     - main
jobs:
        check-TrustedTypes-in-js:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Check policy in JavaScript
                          id: tt
                          uses: t0kapo/tt_codemod@v0.2
                          with:
                                codemod: innerhtml.js
                                js-policy-file-path: static/js/innerhtml.js
                        - uses: stefanzweifel/git-auto-commit-action@v4.12.0
                          with:
                                  commit_message: Checked tt and policy.
